// <auto-generated />
using System;
using MemberRegister.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MemberRegister.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221007165929_Init create")]
    partial class Initcreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MemberRegister.Core.Entities.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Postaladdress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Member");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Adress 1",
                            CreationDate = new DateTime(2022, 10, 7, 18, 59, 29, 384, DateTimeKind.Local).AddTicks(757),
                            Firstname = "Fornamn 1",
                            LastUpdatedDate = new DateTime(2022, 10, 7, 18, 59, 29, 384, DateTimeKind.Local).AddTicks(757),
                            Lastname = "Efternamn 1",
                            Postaladdress = "Postort 1",
                            Postcode = "111111"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Adress 2",
                            CreationDate = new DateTime(2022, 10, 7, 18, 59, 29, 384, DateTimeKind.Local).AddTicks(757),
                            Firstname = "Fornamn 2",
                            LastUpdatedDate = new DateTime(2022, 10, 7, 18, 59, 29, 384, DateTimeKind.Local).AddTicks(757),
                            Lastname = "Efternamn 2",
                            Postaladdress = "Postort 2",
                            Postcode = "222222"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Adress 3",
                            CreationDate = new DateTime(2022, 10, 7, 18, 59, 29, 384, DateTimeKind.Local).AddTicks(757),
                            Firstname = "Fornamn 3",
                            LastUpdatedDate = new DateTime(2022, 10, 7, 18, 59, 29, 384, DateTimeKind.Local).AddTicks(757),
                            Lastname = "Efternamn 3",
                            Postaladdress = "Postort 3",
                            Postcode = "333333"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
